In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [7]:
Data=pd.read_csv(r"C:\Users\Admin\Desktop\monkey pox1.csv")

In [8]:
Data

Patient_ID     Systemic Illness  Rectal Pain  Sore Throat  \
0             P0                 None        False         True   
1             P1                Fever         True        False   
2             P2                Fever        False         True   
3             P3                 None         True        False   
4             P4  Swollen Lymph Nodes         True         True   
...          ...                  ...          ...          ...   
24995     P24995                 None         True         True   
24996     P24996                Fever        False         True   
24997     P24997                 None         True         True   
24998     P24998  Swollen Lymph Nodes        False         True   
24999     P24999  Swollen Lymph Nodes        False        False   

       Penile Oedema  Oral Lesions  Solitary Lesion  Swollen Tonsils  \
0               True          True            False             True   
1               True          True            False            False   
2               True         False            False            False   
3              False         False             True             True   
4               True         False            False             True   
...              ...           ...              ...              ...   
24995          False          True             True            False   
24996           True         False             True             True   
24997          False         False             True             True   
24998          False          True             True             True   
24999           True         False            False             True   

       HIV Infection  Sexually Transmitted Infection MonkeyPox  
0              False                           False  Negative  
1               True                           False  Positive  
2               True                           False  Positive  
3               True                           False  Positive  
4               True                           False  Positive  
...              ...                             ...       ...  
24995          False                            True  Positive  
24996           True                            True  Positive  
24997          False                           False  Positive  
24998          False                           False  Negative  
24999           True                           False  Positive  

[25000 rows x 11 columns]

In [9]:
Data.head()

Patient_ID     Systemic Illness  Rectal Pain  Sore Throat  Penile Oedema  \
0         P0                 None        False         True           True   
1         P1                Fever         True        False           True   
2         P2                Fever        False         True           True   
3         P3                 None         True        False          False   
4         P4  Swollen Lymph Nodes         True         True           True   

   Oral Lesions  Solitary Lesion  Swollen Tonsils  HIV Infection  \
0          True            False             True          False   
1          True            False            False           True   
2         False            False            False           True   
3         False             True             True           True   
4         False            False             True           True   

   Sexually Transmitted Infection MonkeyPox  
0                           False  Negative  
1                           False  Positive  
2                           False  Positive  
3                           False  Positive  
4                           False  Positive

In [10]:
Data.describe()

Patient_ID Systemic Illness Rectal Pain Sore Throat Penile Oedema  \
count       25000            25000       25000       25000         25000   
unique      25000                4           2           2             2   
top            P0            Fever       False        True          True   
freq            1             6382       12655       12554         12612   

       Oral Lesions Solitary Lesion Swollen Tonsils HIV Infection  \
count         25000           25000           25000         25000   
unique            2               2               2             2   
top           False            True            True          True   
freq          12514           12527           12533         12584   

       Sexually Transmitted Infection MonkeyPox  
count                           25000     25000  
unique                              2         2  
top                             False  Positive  
freq                            12554     15909

In [11]:
Data.isnull().any()

Patient_ID                        False
Systemic Illness                  False
Rectal Pain                       False
Sore Throat                       False
Penile Oedema                     False
Oral Lesions                      False
Solitary Lesion                   False
Swollen Tonsils                   False
HIV Infection                     False
Sexually Transmitted Infection    False
MonkeyPox                         False
dtype: bool

In [13]:
Data["Systemic Illness"].unique()

array(['None', 'Fever', 'Swollen Lymph Nodes', 'Muscle Aches and Pain'],
      dtype=object)

In [15]:
Data.shape

(25000, 11)

In [16]:
Data.columns

Index(['Patient_ID', 'Systemic Illness', 'Rectal Pain', 'Sore Throat',
       'Penile Oedema', 'Oral Lesions', 'Solitary Lesion', 'Swollen Tonsils',
       'HIV Infection', 'Sexually Transmitted Infection', 'MonkeyPox'],
      dtype='object')

In [17]:
d=Data.iloc[:,1:]
cols = ['Systemic Illness', 'Rectal Pain', 'Sore Throat', 'Penile Oedema',
       'Oral Lesions', 'Solitary Lesion', 'Swollen Tonsils', 'HIV Infection',
       'Sexually Transmitted Infection', 'MonkeyPox']

In [18]:
df=Data.iloc[:,1:]

In [19]:
df

Systemic Illness  Rectal Pain  Sore Throat  Penile Oedema  \
0                     None        False         True           True   
1                    Fever         True        False           True   
2                    Fever        False         True           True   
3                     None         True        False          False   
4      Swollen Lymph Nodes         True         True           True   
...                    ...          ...          ...            ...   
24995                 None         True         True          False   
24996                Fever        False         True           True   
24997                 None         True         True          False   
24998  Swollen Lymph Nodes        False         True          False   
24999  Swollen Lymph Nodes        False        False           True   

       Oral Lesions  Solitary Lesion  Swollen Tonsils  HIV Infection  \
0              True            False             True          False   
1              True            False            False           True   
2             False            False            False           True   
3             False             True             True           True   
4             False            False             True           True   
...             ...              ...              ...            ...   
24995          True             True            False          False   
24996         False             True             True           True   
24997         False             True             True          False   
24998          True             True             True          False   
24999         False            False             True           True   

       Sexually Transmitted Infection MonkeyPox  
0                               False  Negative  
1                               False  Positive  
2                               False  Positive  
3                               False  Positive  
4                               False  Positive  
...                               ...       ...  
24995                            True  Positive  
24996                            True  Positive  
24997                           False  Positive  
24998                           False  Negative  
24999                           False  Positive  

[25000 rows x 10 columns]

# Label Encoding

In [20]:
from sklearn.preprocessing import LabelEncoder
l1=LabelEncoder()
# df['']= label_encoder.fit_transform(df['species'])
  
# df['species'].unique()
l1.fit_transform(cols)

array([9, 4, 7, 3, 2, 6, 8, 0, 5, 1], dtype=int64)

In [21]:
df[cols] = df[cols].apply(LabelEncoder().fit_transform)


In [22]:
df.head()

Systemic Illness  Rectal Pain  Sore Throat  Penile Oedema  Oral Lesions  \
0                 2            0            1              1             1   
1                 0            1            0              1             1   
2                 0            0            1              1             0   
3                 2            1            0              0             0   
4                 3            1            1              1             0   

   Solitary Lesion  Swollen Tonsils  HIV Infection  \
0                0                1              0   
1                0                0              1   
2                0                0              1   
3                1                1              1   
4                0                1              1   

   Sexually Transmitted Infection  MonkeyPox  
0                               0          0  
1                               0          1  
2                               0          1  
3                               0          1  
4                               0          1

In [24]:
df.tail()

Systemic Illness  Rectal Pain  Sore Throat  Penile Oedema  \
24995                 2            1            1              0   
24996                 0            0            1              1   
24997                 2            1            1              0   
24998                 3            0            1              0   
24999                 3            0            0              1   

       Oral Lesions  Solitary Lesion  Swollen Tonsils  HIV Infection  \
24995             1                1                0              0   
24996             0                1                1              1   
24997             0                1                1              0   
24998             1                1                1              0   
24999             0                0                1              1   

       Sexually Transmitted Infection  MonkeyPox  
24995                               1          1  
24996                               1          1  
24997                               0          1  
24998                               0          0  
24999                               0          1

In [25]:
df.corr()

Systemic Illness  Rectal Pain  Sore Throat  \
Systemic Illness                        1.000000     0.002102    -0.001614   
Rectal Pain                             0.002102     1.000000     0.006214   
Sore Throat                            -0.001614     0.006214     1.000000   
Penile Oedema                           0.006536     0.005312     0.009082   
Oral Lesions                           -0.001075     0.007747    -0.000795   
Solitary Lesion                        -0.012278     0.001147    -0.003609   
Swollen Tonsils                        -0.001018     0.002113    -0.002011   
HIV Infection                          -0.004664     0.005764     0.000771   
Sexually Transmitted Infection         -0.005868     0.000666    -0.001901   
MonkeyPox                              -0.010769     0.140727     0.063385   

                                Penile Oedema  Oral Lesions  Solitary Lesion  \
Systemic Illness                     0.006536     -0.001075        -0.012278   
Rectal Pain                          0.005312      0.007747         0.001147   
Sore Throat                          0.009082     -0.000795        -0.003609   
Penile Oedema                        1.000000      0.003850         0.002781   
Oral Lesions                         0.003850      1.000000        -0.005198   
Solitary Lesion                      0.002781     -0.005198         1.000000   
Swollen Tonsils                      0.000536     -0.007757         0.002874   
HIV Infection                        0.003620     -0.012153        -0.002335   
Sexually Transmitted Infection      -0.005722     -0.002725         0.009849   
MonkeyPox                            0.061905      0.051955         0.037471   

                                Swollen Tonsils  HIV Infection  \
Systemic Illness                      -0.001018      -0.004664   
Rectal Pain                            0.002113       0.005764   
Sore Throat                           -0.002011       0.000771   
Penile Oedema                          0.000536       0.003620   
Oral Lesions                          -0.007757      -0.012153   
Solitary Lesion                        0.002874      -0.002335   
Swollen Tonsils                        1.000000      -0.004258   
HIV Infection                         -0.004258       1.000000   
Sexually Transmitted Infection        -0.006469       0.001309   
MonkeyPox                              0.013221       0.146192   

                                Sexually Transmitted Infection  MonkeyPox  
Systemic Illness                                     -0.005868  -0.010769  
Rectal Pain                                           0.000666   0.140727  
Sore Throat                                          -0.001901   0.063385  
Penile Oedema                                        -0.005722   0.061905  
Oral Lesions                                         -0.002725   0.051955  
Solitary Lesion                                       0.009849   0.037471  
Swollen Tonsils                                      -0.006469   0.013221  
HIV Infection                                         0.001309   0.146192  
Sexually Transmitted Infection                        1.000000   0.123376  
MonkeyPox                                             0.123376   1.000000

In [26]:
df.MonkeyPox.value_counts()

1    15909
0     9091
Name: MonkeyPox, dtype: int64

# Imbalancing Technique

In [27]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [28]:
from imblearn.over_sampling import SMOTE
from collections import Counter 
s=SMOTE()
x_resample,y_resample=s.fit_resample(x,y)
print(Counter(y_resample))

Counter({0: 15909, 1: 15909})


In [29]:
# from sklearn.preprocessing import StandardScaler
# ss=StandardScaler()
# ss.fit_transform(x_resample)

# Train Test Split

In [33]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_resample,y_resample,test_size=0.25,random_state=110)

In [34]:
print(Counter(y_train))

Counter({1: 12070, 0: 11793})


# Logistic Regression

In [35]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [38]:
sample1=x_test.iloc[:5,:]
sample1

Systemic Illness  Rectal Pain  Sore Throat  Penile Oedema  \
4114                  1            0            0              0   
7518                  3            0            1              1   
8851                  3            1            1              1   
762                   0            1            1              1   
22301                 0            0            1              0   

       Oral Lesions  Solitary Lesion  Swollen Tonsils  HIV Infection  \
4114              1                1                0              1   
7518              1                0                0              0   
8851              1                1                0              0   
762               0                1                1              1   
22301             1                0                0              0   

       Sexually Transmitted Infection  
4114                                1  
7518                                0  
8851                                0  
762                                 0  
22301                               0

In [39]:
y=y_test.iloc[:5]
y

4114     1
7518     1
8851     1
762      1
22301    0
Name: MonkeyPox, dtype: int32

In [40]:
y_pred=model.predict(sample1)
y_pred

array([1, 0, 1, 1, 0])

In [42]:
sample2=x_test.iloc[6:10,:]
sample2

Systemic Illness  Rectal Pain  Sore Throat  Penile Oedema  \
13370                 3            1            1              0   
31389                 2            1            0              0   
16250                 2            0            0              1   
29481                 3            1            0              0   

       Oral Lesions  Solitary Lesion  Swollen Tonsils  HIV Infection  \
13370             0                0                0              1   
31389             0                1                1              0   
16250             0                1                1              1   
29481             0                0                1              0   

       Sexually Transmitted Infection  
13370                               1  
31389                               1  
16250                               1  
29481                               1

In [43]:
y=y_test.iloc[6:10]
y

13370    1
31389    0
16250    1
29481    0
Name: MonkeyPox, dtype: int32

In [44]:
ypred=model.predict(sample2)
ypred

array([1, 1, 1, 0])

In [49]:
from sklearn.metrics import accuracy_score
ac1=round(accuracy_score(y_train,model.predict(x_train))*100,4)
print("Accurancy score of Training:",ac1)
ac=round(accuracy_score(y_test,model.predict(x_test))*100,4)
print("Accuracy score of Testing:",ac)

Accurancy score of Training: 61.4382
Accuracy score of Testing: 60.616


# K Nearest Neighbors


In [50]:
from sklearn.neighbors import KNeighborsClassifier
k=KNeighborsClassifier(n_neighbors=10,metric="minkowski",p=1)
k.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=10, p=1)

In [51]:
k.predict(sample1)

array([1, 0, 1, 0, 0])

In [52]:
k.predict(sample2)

array([1, 0, 1, 0])

In [53]:
from sklearn.metrics import accuracy_score
ac=round(accuracy_score(y_test,k.predict(x_test))*100,4)
print(ac)

61.8228
